### ISSUE TITLE
[BUG]Matrix config can't work

### ISSUE THREAD

**Issue by CkaDebug** [TalentsRC/Talents-AntiCheat-Config#1]
### 描述错误

can't work ,waiting fix,pls use default checks.yml

### 日志文件或 图像/视频

none

### 复现行动

none

### 预期行为

none

### 平台

- 服务器核心: any
- 服务器类型: any
- 服务器版本: any
- 反作弊配置版本: any

### 其他补充?

none

**Comment by TalentsRC** [comment]
fix
